

export enum MonoBehaviourName {
    COLLISION_VEC_VISUALIZER = 'COLLISION_VEC_VISUALIZER',
    COLLISION_RADIUS_VISUALIZER = 'COLLISION_RADIUS_VISUALIZER',
    ROUTE_CONTROLLER = 'ROUTE_CONTROLLER',
    MOTION_CONTROLLER = 'MOTION_CONTROLLER',
    STATE_CONTROLLER = 'STATE_CONTROLLER'
}